name: Qwen/Qwen3-8B-uncertainty
base_model_id: Qwen/Qwen3-8B
lora_weight_path: improve_llm_linguistic_confidence/res/weight/qwen3_8b_lora_weight
save_path: improve_llm_linguistic_confidence/res/model
temperature: 0.6
top_p: 0.95
top_k: 20
min_p: 0.0
thinking: True
max_tokens: 32768