# defaults:
#  - qa_model: gpt-5-mini
#  - confidence_extractor: linguistic_confidence_base
#  - dataset: simple_qa
#  - metrics: default
#  - pre_runned_batch: vanilla-gpt-5-mini


# hydra:
#   run:
#     dir: llm_linguistic_confidence_study/results/${dataset.name}/${qa_model.name}/${confidence_extractor.name}/${now:%Y-%m-%d_%H-%M-%S}

# seed: 42
defaults:
 - qa_model: gpt-5-mini
 - confidence_extractor: semantic_uncertainty
 - dataset: simple_qa
 - metrics: default
 - pre_runned_batch: vanilla-su-gpt-5-mini


hydra:
  run:
    dir: llm_linguistic_confidence_study/results/${dataset.name}/${qa_model.name}/${confidence_extractor.name}/${now:%Y-%m-%d_%H-%M-%S}

seed: 42
