defaults:
 - qa_model: gpt-5-nano
 - confidence_extractor: linguistic_confidence
 - dataset: simple_qa
 - metrics: all
 - pre_runned_batch: vanilla-gpt-5-nano


hydra:
  run:
    dir: llm_linguistic_confidence_study/results/${dataset.name}/${qa_model.name}/${confidence_extractor.name}/${now:%Y-%m-%d_%H-%M-%S}

seed: 42