qa_batch_id: 456bf276-d82a-43b7-a4d0-f1d15225e8f2
grader_batch_id: batch_68b1d9457f70819096e5f07e4e87923d
semantic_ids_path: llm_linguistic_confidence_study/pretrained_weights/semantic_ids_Qwen3-235B-A22B-Instruct-2507-tput.npy